name: Build Mailcow Docker Bundle

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout empty repo
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Check Docker version
        run: docker --version

      # - name: show default daemon json content
      #   run: cat /etc/docker/daemon.json

      - name: Pull Mailcow images
        run: |
          docker pull ghcr.io/mailcow/unbound:1.24
          docker pull mariadb:10.11
          docker pull redis:7.4.2-alpine
          docker pull ghcr.io/mailcow/clamd:
