name: Pull & Package memcached:alpine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建 release
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull memcached:alpine image
        run: |
          docker pull memcached:alpine

      - name: Save image to tar
        run: |
          mkdir -p bundle
          docker save memcached:alpine -o bundle/memcached-alpine.tar

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: memcached-bundle
          name: memcached-alpine
          files: bundle/memcached-alpine.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
